/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as PcRecords9f2aRouteImport } from './routes/pc-records-9f2a'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as IndexRouteImport } from './routes/index'

const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const PcRecords9f2aRoute = PcRecords9f2aRouteImport.update({
  id: '/pc-records-9f2a',
  path: '/pc-records-9f2a',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/pc-records-9f2a': typeof PcRecords9f2aRoute
  '/recruitment': typeof RecruitmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/pc-records-9f2a': typeof PcRecords9f2aRoute
  '/recruitment': typeof RecruitmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/pc-records-9f2a': typeof PcRecords9f2aRoute
  '/recruitment': typeof RecruitmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consultation' | '/pc-records-9f2a' | '/recruitment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consultation' | '/pc-records-9f2a' | '/recruitment'
  id: '__root__' | '/' | '/consultation' | '/pc-records-9f2a' | '/recruitment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultationRoute: typeof ConsultationRoute
  PcRecords9f2aRoute: typeof PcRecords9f2aRoute
  RecruitmentRoute: typeof RecruitmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc-records-9f2a': {
      id: '/pc-records-9f2a'
      path: '/pc-records-9f2a'
      fullPath: '/pc-records-9f2a'
      preLoaderRoute: typeof PcRecords9f2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultationRoute: ConsultationRoute,
  PcRecords9f2aRoute: PcRecords9f2aRoute,
  RecruitmentRoute: RecruitmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
